// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2026, 4, 29, 1, 39, 57, 197, DateTimeKind.Utc).AddTicks(3652),
                            Name = "IPL Finals 2025",
                            Venue = "Hyderabad Stadium"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            RowVersion = new byte[0],
                            SeatNumber = "A1",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            EventId = 1,
                            RowVersion = new byte[0],
                            SeatNumber = "A2",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            EventId = 1,
                            RowVersion = new byte[0],
                            SeatNumber = "A3",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            EventId = 1,
                            RowVersion = new byte[0],
                            SeatNumber = "A4",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            EventId = 1,
                            RowVersion = new byte[0],
                            SeatNumber = "A5",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            EventId = 1,
                            RowVersion = new byte[0],
                            SeatNumber = "A6",
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            EventId = 1,
                            RowVersion = new byte[0],
                            SeatNumber = "A7",
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            EventId = 1,
                            RowVersion = new byte[0],
                            SeatNumber = "A8",
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            EventId = 1,
                            RowVersion = new byte[0],
                            SeatNumber = "A9",
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            EventId = 1,
                            RowVersion = new byte[0],
                            SeatNumber = "A10",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.HasOne("Domain.Entities.Event", "Event")
                        .WithMany("Seats")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
